Pizzaria_6320048/Models/Cardapio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pizzaria_6320048.Models
{
    public class Cardapio
    {
        public int Id { get; set; }
        [Required]
        public string Pizza { get; set; }
        public string Sabor { get; set; }
        public decimal ValorInt { get; set; }
        public decimal ValorBrot { get; set; }
    }
}

Pizzaria_6320048/Controllers/CardapioController.cs
using MySql.Data.MySqlClient;
using Pizzaria_6320048.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pizzaria_6320048.Controllers
{
    public class CardapioController : Controller
    {
        MySqlConnection conn;
        MySqlDataReader dr;

        string StrConn;
        string StrQuery;

        // GET: Cardapio
        public ActionResult Index()
        {
            StrConn = "Server=localhost;Database=cardapio_pizza;Uid=root;Pwd=74859623Mamaed10";
            List<Cardapio> lstCardapios = new List<Cardapio>();

            conn = new MySqlConnection(StrConn);
            StrQuery = "SELECT * FROM cardapios order by Id";

            MySqlCommand comando = new MySqlCommand(StrQuery, conn);
            conn.Open();

            dr = comando.ExecuteReader();

            while (dr.Read())
            {
                Cardapio cardapio = new Cardapio();

                cardapio.Id = Convert.ToInt32(dr["id"]);
                cardapio.Pizza = Convert.ToString(dr["Pizza"]);
                cardapio.Sabor = Convert.ToString(dr["Sabor"]);
                cardapio.ValorInt = Convert.ToDecimal(dr["ValorInt"]);
                cardapio.ValorBrot = Convert.ToDecimal(dr["ValorBrot"]);

                lstCardapios.Add(cardapio);
            }

            return View(lstCardapios);
        }

        public ActionResult Index1()
        {
            StrConn = "Server=localhost;Database=cardapio_pizza;Uid=root;Pwd=74859623Mamaed10";
            List<Cardapio> lstCardapios = new List<Cardapio>();

            conn = new MySqlConnection(StrConn);
            StrQuery = "SELECT * FROM cardapios order by Id";

            MySqlCommand comando = new MySqlCommand(StrQuery, conn);
            conn.Open();

            dr = comando.ExecuteReader();

            while (dr.Read())
            {
                Cardapio cardapio = new Cardapio();

                cardapio.Id = Convert.ToInt32(dr["id"]);
                cardapio.Pizza = Convert.ToString(dr["Pizza"]);
                cardapio.Sabor = Convert.ToString(dr["Sabor"]);
                cardapio.ValorInt = Convert.ToDecimal(dr["ValorInt"]);
                cardapio.ValorBrot = Convert.ToDecimal(dr["ValorBrot"]);

                lstCardapios.Add(cardapio);
            }

            return View(lstCardapios);
        }

        public ActionResult NovaPizza()
        {          
            return View();
        }

        public ActionResult SalvarPizza(Cardapio cardapio)
        {
            if (ModelState.IsValid)
            {
                StrConn = "Server=localhost;Database=cardapio_pizza;Uid=root;Pwd=74859623Mamaed10";

                conn = new MySqlConnection(StrConn);
                StrQuery = "INSERT INTO cardapios(Pizza, Sabor, ValorInt, ValorBrot) VALUES (@Pizza, @Sabor, @ValorInt, @ValorBrot)";
                MySqlCommand comando = new MySqlCommand(StrQuery, conn);
                comando.Parameters.AddWithValue("@Pizza", cardapio.Pizza);
                comando.Parameters.AddWithValue("@Sabor", cardapio.Sabor);
                comando.Parameters.AddWithValue("@ValorInt", cardapio.ValorInt);
                comando.Parameters.AddWithValue("@ValorBrot", cardapio.ValorBrot);
                conn.Open();
                comando.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            return View(cardapio);
            
        }

        public ActionResult DeletarPizza(Cardapio cardapio)
        {
            
                StrConn = "Server=localhost;Database=cardapio_pizza;Uid=root;Pwd=74859623Mamaed10";

                conn = new MySqlConnection(StrConn);
                StrQuery = "DELETE from cardapios WHERE Id=@Id;";
                MySqlCommand comando = new MySqlCommand(StrQuery, conn);
                comando.Parameters.AddWithValue("@Id", cardapio.Id);
                conn.Open();
                comando.ExecuteNonQuery();
                return RedirectToAction("Index");
        }

        public ActionResult EditarPizza(Cardapio cardapio)
        {
            if (ModelState.IsValid)
            {
                StrConn = "Server=localhost;Database=cardapio_pizza;Uid=root;Pwd=74859623Mamaed10";

                conn = new MySqlConnection(StrConn);
                StrQuery = "UPDATE cardapios SET Pizza = @Pizza, Sabor = @Sabor, ValorInt = @ValorInt, ValorBrot = @ValorBrot WHERE Id = @Id;";
                MySqlCommand comando = new MySqlCommand(StrQuery, conn);
                comando.Parameters.AddWithValue("@Id", cardapio.Id);
                comando.Parameters.AddWithValue("@Pizza", cardapio.Pizza);
                comando.Parameters.AddWithValue("@Sabor", cardapio.Sabor);
                comando.Parameters.AddWithValue("@ValorInt", cardapio.ValorInt);
                comando.Parameters.AddWithValue("@ValorBrot", cardapio.ValorBrot);
                conn.Open();
                comando.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            return View(cardapio);
        }
    }
}

Pizzaria_6320048/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pizzaria_6320048.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Pizzaria_6320048/Views/Cardapio/DeletarPizza.cshtml
@model Pizzaria_6320048.Models.Cardapio

@{
    ViewBag.Title = "DeletarPizza";
}

<h2>DeletarPizza</h2>

<h3>Qual Pizza você deseja deletar?</h3>
<div>
    <h4>Cardapio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pizza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pizza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sabor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sabor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorBrot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorBrot)
        </dd>

    </dl>

    @using (Html.BeginForm("DeletarPizza", "Cardapio")) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Pizzaria_6320048/Views/Cardapio/EditarPizza.cshtml
@model Pizzaria_6320048.Models.Cardapio

@{
    ViewBag.Title = "EditarPizza";
}

<h2>EditarPizza</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cardapio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Pizza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pizza, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pizza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sabor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sabor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sabor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorBrot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorBrot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorBrot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pizzaria_6320048/Views/Cardapio/Index.cshtml
@model IEnumerable<Pizzaria_6320048.Models.Cardapio>

@{
    ViewBag.Title = "Index";
}

<center><img src="~/imgs/CardapioView.jpg" style="bottom: 0px; width: 100%"/> </center>
    <br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pizza)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sabor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorInt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorBrot)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Pizza)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sabor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorInt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorBrot)
        </td>
    </tr>
}
</table>

<form method="get" action="~/Cardapio/Index1">
    <center> <button class="btn btn-primary" type="submit">Editar cardápio</button> </center>
</form>

Pizzaria_6320048/Views/Cardapio/Index1.cshtml
@model IEnumerable<Pizzaria_6320048.Models.Cardapio>

@{
    ViewBag.Title = "Index1";
}

<center><img src="~/imgs/EditarCardapioView.jpg" style="bottom: 0px; width: 100%;"/> </center>
<br />


<center>
    <button class="btn btn-outline-info">
        @Html.ActionLink("Adicionar nova Pizza", "NovaPizza")
    </button>
</center>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pizza)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sabor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorInt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorBrot)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pizza)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sabor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorInt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorBrot)
            </td>
            <td>
                @Html.ActionLink("Editar", "EditarPizza", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "DeletarPizza", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<form method="get" action="~/Cardapio/Index">
    <center> <button class="btn btn-primary" type="submit">Voltar à cardápio</button> </center>
</form>

Pizzaria_6320048/Views/Cardapio/NovaPizza.cshtml
@model Pizzaria_6320048.Models.Cardapio

@{
    ViewBag.Title = "NovaPizza";
}

<h2>NovaPizza</h2>


@using (Html.BeginForm("SalvarPizza", "Cardapio")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cardapio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pizza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pizza, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pizza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sabor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sabor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sabor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorBrot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorBrot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorBrot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pizzaria_6320048/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/imgs/FundoBlog.png" />
            <div class="container">
                <div class="carousel-caption text-left">
                    <h1>Último post (Instagram)</h1>
                    <p>Acesse abaixo o link</p>
                    <p><a class="btn btn-lg btn-primary" href="~/Cardapio/#postagens">Acessar posts</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/imgs/FundoBlog.png" />
            <div class="container">
                <div class="carousel-caption">
                    <h1>Sobre nós!</h1>
                    <p>Somos uma das pizzarias mais prestigiadas do mundo, conheça sobre nós e funcionários.</p>
                    <p><a class="btn btn-lg btn-primary" href="~/Home/#sobre">Saiba mais</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/imgs/FundoBlog.png" /> 
            <div class="container">
                <div class="carousel-caption text-right">
                    <h1>Entre em contato com a gente!</h1>
                    <p>Equipe totalmente pronta para lhe atender e dar total suporte.</p>
                    <p><a class="btn btn-lg btn-primary" href="~/Home/#contato">Entrar em contato</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<a name="postagens"></a>

Pizzaria_6320048/Views/Home/Blog.cshtml
@{
    ViewBag.Title = "Blog";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pizzaria_6320048/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Pizzaria";
}
<!--Carrosel-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/imgs/pizza1.jpg" />
            <div class="container">
                <div class="carousel-caption text-left">
                    <h1>Melhor Pizzaria da região e do Brasil!</h1>
                    <p>Consulte nosso cardápio e preços.</p>
                    <p><a class="btn btn-lg btn-primary" href="~/Cardapio/Index">Ver cardápio</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/imgs/pizza2.jpg" />
            <div class="container">
                <div class="carousel-caption">
                    <h1>Sobre nós!</h1>
                    <p>Somos uma das pizzarias mais prestigiadas do mundo, conheça sobre nós e funcionários.</p>
                    <p><a class="btn btn-lg btn-primary" href="~/Home/#sobre">Saiba mais</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/imgs/pizza3.jpg"/>
            <div class="container">
                <div class="carousel-caption text-right">
                    <h1>Entre em contato com a gente!</h1>
                    <p>Equipe totalmente pronta para lhe atender e dar total suporte.</p>
                    <p><a class="btn btn-lg btn-primary" href="~/Home/#contato">Entrar em contato</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row mb-4">
    
    <div class="col-md-12">
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">Cardápio</strong>
                <h3 class="mb-0">Featured post</h3>
                <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.Donec sit amet eros sit amet felis gravida pulvinar. Mauris sed sem vel mi feugiat sollicitudin. Fusce mattis neque vel vulputate malesuada. Etiam aliquam libero augue, nec luctus felis tempor ac. Donec semper pulvinar orci ut finibus. Donec nec fringilla odio. Aliquam erat volutpat.</p> <br />
                <a href="~/Cardapio/Index" class="stretched-link">Acessar cardápio!</a>
            </div>
            <a name="cardapio"></a>
            <div class="col-auto d-none d-lg-block">
                <img class="bd-placeholder-img" width="400" height="300" src="~/imgs/Sobre.jpg" />
            </div>
        </div>
    </div>
</div>

<div class="col-md-12">
   <center><img src="~/imgs/Cardapio.jpg" class="col-md-12"/> </center>
    <br />
</div>

    <hr />
    <!--Sobre Nós-->
    <div class="marketing">
        <center>
            <div>
                <a name="sobre"></a>
                <h1> Sobre Nós</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In in massa eu augue accumsan rutrum eget nec augue. Vestibulum egestas semper auctor. Suspendisse scelerisque ipsum eget est volutpat volutpat eu eget libero. Donec sit amet eros sit amet felis gravida pulvinar. Mauris sed sem vel mi feugiat sollicitudin. Fusce mattis neque vel vulputate malesuada. Etiam aliquam libero augue, nec luctus felis tempor ac. Donec semper pulvinar orci ut finibus. Donec nec fringilla odio. Aliquam erat volutpat. Donec quis ligula maximus, sagittis erat non, porttitor tellus.</p>
            </div>
        </center>
        <br />
        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="~/imgs/personagem1.jpg" />
                <h2>Heading</h2>
                <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
                @*<p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>*@
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="~/imgs/personagem2.jpg" />
                <h2>Heading</h2>
                <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
                @*<p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>*@
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="~/imgs/personagem3.jpg" />
                <h2>Heading</h2>
                <p>And lastly this, the third column of representative placeholder content.</p>
                @*<p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>*@
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
    </div>
    <hr />
    <a name="contato"></a>
    <center>  <h1>Contato</h1> </center>

        <div>
            <form name="frmCadastro" class="form col-md-12">
                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="txNome">Nome</label>
                                <input class="form-control form-control-lg" type="text" id="txNome" name="txNome" onblur="verificaNome();" />
                            </div>
                            <div class="col-md-6">
                                <label for="txCPF">CPF</label>
                                <input class="form-control form-control-lg" type="text" id="txCPF" name="txCPF" onblur="testaCPF();" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label for="txEmail">E-mail</label>
                                <input class="form-control form-control-lg" type="email" id="txEmail" name="txEmail" required="required" />
                            </div>
                            <div class="col-md-6">
                                <label class="control-label" for="txFone">Telefone</label>
                                <input class="form-control form-control-lg" type="text" id="txFone" name="txFone" onblur="verificaFone();" />
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-4">
                                <input class="btn btn-primary" type="submit" onclick="recebeInfo();" value="Enviar dados" />
                            </div>
                            <div class="col-md-8">
                                <input class="form-control form-control-lg" type="text" id="txAlerta" name="txAlerta" />
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>

        <hr />
        <div>
            <center> <a href="#topo">Clique aqui para voltar ao topo</a> </center>
        </div>